controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger
      - right_finger
  - name: fake_camera_controller
    type: $(arg fake_execution_type)
    joints:
      - pan
      - tilt
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []