# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

pan_controller:
  type: effort_controllers/JointPositionController
  joint: pan
  pid: {p: 30.0, i: 1.0, d: 0.1}

tilt_controller:
  type: effort_controllers/JointPositionController
  joint: tilt
  pid: {p: 30.0, i: 1.0, d: 0.1}
