arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_angle
    - wrist_rotate
    - forearm_roll
  gains:
    waist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_angle:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_rotate:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger
    - right_finger
  gains:
    left_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
pan_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - pan
  gains:
    pan:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
tilt_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - tilt
  gains:
    tilt:
      p: 100
      d: 1
      i: 1
      i_clamp: 1